var LOCALIZATION = {
    COMMON: {
        BACK: "Trở lại",
        MANAGE: "Hiệu chỉnh",
        ADD: "Thêm mới",
        EDIT: "Hiệu chỉnh",
        REMOVE: "Xóa",
        CONFIRM_DELETE_MESSAGE: "Bạn có chắc muốn xóa {0} này",
        CONFIRM_DELETE_OK: "Xóa",
        CONFIRM_DELETE_CANCEL: "Hủy bỏ",
        CONFIRM_TITLE: "Chú ý",
        ITEM_NOT_SELECTED: "Chưa chọn phần tử",
        DETAIL_TITLE: "Thông tin ",
        ALL: "Tất cả",
        SAVE: "Lưu",
        SAVECLOSE: "Lưu và đóng",
        CANCEL: "Hủy bỏ",
        ACCEPT: "Đồng ý",
        REFUSE: "Từ chối",
        GRAPH_VIEW: "Lượt đồ",
        SAVE_SUCCESS: "Lưu thành công",
        SAVE_ERROR: "Lưu không thành công",
        CONFIRM_UNSAVED: "Thao tác này có thể làm mất dữ liệu chưa lưu, ban có thực sự muốn thực hiện thao tác này?",
        ORDER: "Sắp xếp",
        UPLOAD: "Upload",
        CONFIRM: "Bạn có chắc muốn thực hiện tác vụ này?",
        CONFIRM_ASSIGN: "Bạn có muốn phân công cho chính bạn không ?",
        NOT_ENOUGHT_UPLOAD_FILE: "Chưa upload đủ số lượng file",
        NEW: "new",
        UPDATE: "update",
        FILTER: "Filter",
        DELETE_SUCCESS: "Xóa phần tử thành công",
        CHANGE: "Thay đổi",
        COPY: "Sao chép",
        SEARCH: "Tìm kiếm",
        PRINT: "In"
    },
    BRANCH: {
        TITLE: "Chi nhánh",
        PROPERTY_NAME: "Tên chi nhánh",
        CODE: "Mã",
        ADDRESS: "Địa chỉ",
        REGIONS: "Vùng miền"
    },
    ORGANIZATION: {
        TITLE: "Tổ chức",
        BRANCH_NOT_SELECTED: "Chưa chọn Chi nhánh",
    },
    DEPARTMENT: {
        TITLE: "Phòng ban",
        PROPERTY_NAME: "Tên Phòng ban",
        SUB_TITLE: "Chi nhánh & Phòng ban"
    },
    SUBDEPARTMENT: {
        TITLE: "Phòng Giao dịch",
        PROPERTY_NAME: "Tên Phòng Giao dịch"
    },
    POSITION: {
        TITLE: "Bộ phận",
        PROPERTY_NAME: "Tên Bộ phận",
        CODE: "Mã Bộ phận"
    },
    PRODUCT: {
        TITLE: "Sản phẩm",
        INFORMATION: "Thông tin Sản phẩm",
        OVERVIEW: "Overview",
        OVERVIEW_GRAPHVIEW: "Graph View",
        PROPERTY_NAME: "Tên Sản phẩm",
        PROPERTY_CODE: "Mã Sản phẩm",
        PROPERTY_CRFORM: "Biểu mẫu tổng hợp CR",
        SET_CRFORM: "Thiết lập Biểu mẫu CR",
        STATUS: "Trạng thái",
        PUBLISH: "Publish",
        LOCK: "Lock",
        SBANK: "SBank"
    },
    PRODUCT_FILE_ATTACHMENT: {
        TITLE: "File Đính kèm",
        PROPERTY_NAME: "Tên File đính kèm",
        NUMBER_SETTING: "Số lượng",
        COPY_COUNT: "Bản phụ",
        PRIMARY_COUNT: "Bản gốc"
    },
    PRODUCT_FORM: {
        TITLE: "Biểu mẫu",
        PROPERTY_NAME: "Tên Biểu mẫu",
        EDIT_CODE_MODE: "Hiệu chỉnh (Code)",
        EDIT_UI_MODE: "Hiệu chỉnh (UI)",
        DESIGNER: "Thiết kế Biểu mẫu",
        FORM_ERROR: "Thông tin chưa đầy đủ",
        FORM_VALIDATE: "Thông tin đầy đủ",
        FORM_CLOSE:"Đóng"
    },
    PRODUCT_MAPPING: {
        BUTTON_TITLE:"Sao chép HS",
        TITLE: "sao chép hồ sơ",
        PROPERTY_NAME:"Data Model"
    },
    WORKFLOW: {
        TITLE: "Quy trình",
        ELEMENT_PHASE: "Giai đoạn",
        ELEMENT_LAYER: "Bộ phận Xử lý",
        ELEMENT_STAGE: "Bước",
        ELEMENT_DECISION: "Quyết định",
        PROPERTY_NAME: "Tên",
        PROPERTY_DURATION: "Thời gian Hoàn thành (giờ)"
    },
    DATAMODEL: {
        TITLE: "Data Model",
        BASE_DATA: "Base Data",
        ARRAY_DATA: "Array Data",
        COMPUTE_DATA: "Compute Data",
        FUNCTION_DATA: "Function Data",
        CLASS_DATA:"Class Data",
        PROPERTY_CODE: "Code",
        PROPERTY_ARRAY: "Options",
        PROPERTY_FUNCTION: "Function",
        PROPERTY_DESCRIPTION: "Mô tả",
        INDEXING: "Biên mục Data Model",
        INDEXING_PROPERTY_NAME: "Tên chỉ mục",
        INDEXING_PROPERTY_TYPE: "Kiểu chỉ mục"
    },
    INDEXING: {
        TITLE: "Biên mục Dữ liệu",
        PROPERTY_CODE: "Code",
        PROPERTY_NAME: "Tên",
        PROPERTY_TYPE: "Kiểu",
        PROPERTY_SEARCH: "Tìm kiếm"
    },
    USER: {
        TITLE: "Người dùng",
        PROPERTY_FULLNAME: "Họ và Tên",
        PROPERTY_LOGIN_NAME: "Tên đăng nhập",
        STAFF: "Nhân viên",
        LEADER:"Lãnh đạo",
        
        PROPERTY_EMAIL: "Email",
        PROPERTY_STATUS: "Trạng thái",
        PROPERTY_PASSWORD: "Mật khẩu",
        PROPERTY_PASSWORD_RETYPE: "Nhập lại mật khẩu",
        PROPERTY_BRANCH_ADMIN: "Quản trị Chi nhánh",
        PROPERTY_STATUS_FALSE: "Khóa",
        PROPERTY_STATUS_TRUE: "Kích hoạt",
        PROPERTY_LEADER: "Chức vụ"
    },
    PROFITMARGIN: {
        TITLE: "Profit Margin",
        ADDTITLE: "Thêm Profit Margin",
        PROPERTY_MANGANH: "Mã ngành",
        PROPERTY_TENNGANH: "Tên ngành",
        PROPERTY_PROFITMARGIN: "Profit Margin",
        PROPERTY_VALUE: "Giá trị"
    },
    APPLICATION: {
        PROCESSING: "Processing",
        DRAFT : "Draft",
        
        NEED_ASSIGN: "Hồ sơ cần phân công",
        MANAGEMENT: "Kiểm soát Hồ sơ",
        CREATE_SUCCESSFUL: "Tạo hồ sơ thành công",
        CURRENT_PHASE: "Giai đoạn hiện tại",
        CURRENT_STAGE: "Bước hiện tại",
        UPLOAD_FILE_FAILED: "Upload file {0} thất bại",
        UPLOAD_FILE_SUCCESSED: "Upload file {0} thành công",
        UPLOAD_FILE_REMOVED_SUCCESSED: "Xóa file {0} thành công",
        VIEW: "Xem",

        TITLE: "Hồ sơ",
        HISTORY: "Lịch sử",
        HISTORY_GRAPH: "Lịch sử (Lượt đồ)",
        CREATE: "Tạo hồ sơ",
        INFORMATION: "Thông tin Hồ sơ",
        WORKFLOW_INFORMATION: "Thông tin Quy trình",
        PROPERTY_PRODUCTNAME: "Sản phẩm",
        PROPERTY_NAME: "Tên hồ sơ",
        PROPERTY_WORKFLOWNAME: "Quy trình",
        PROPERTY_STAGENAME: "Bước",
        PROPERTY_TASKS: "Các Công việc cần hoàn thành",
        APPROVE: "Duyệt Hồ sơ",
        SENDBACK: "Trả lại Hồ sơ",
        APPEND: "Bổ sung Hồ sơ",
        APPEND_APPROVE: "Duyệt bổ sung",
        APPEND_REVIEW: "Xem bổ sung",
        APPEND_USER: "Cán bộ Bổ sung",
        FINISH: "Kết thúc Hồ sơ",
        REMOVE: "Xóa hồ sơ",
        NEXT_STAGE: "Bước tiếp theo",
        NEXT_STAGE_USER: "Người xử lý",
        COMMENT: "Ghi chú",
        FILES: "File đính kèm",
        FILE: "Danh sách File đính kèm",
        FILES_UPDATE: "Danh sách file bổ sung",
        NEED_UPDATE_FILES: "Cần bổ sung hồ sơ",
        FORMS: "Danh sách Biểu mẫu",
        FORM: "Biểu mẫu",
        FORM_DATA: "Thông tin Hồ sơ",
        INBOX: "Published Document",
        ALLINBOX:"Tất cả hồ sơ",
        
        
        SENDBOX: "Sent Box",
        DEPARTMENT_SEND: "Hồ sơ Phòng gửi",
        BOOKMARK: "Hồ sơ đánh dấu",
        DO_BOOKMARK: "Đánh dấu Hồ sơ",
        ASSIGN: "Phân công",
        DEPARTMENT_ASSIGNED: "Phòng ban xử lý",
        POSITION_ASSIGNED: "Khối xử lý",
        USER_ASSIGNED: "Người xử lý",
        USER_CC: "CC",
        UNASSIGNED: "Đang chờ phân công",
        
               
        COMPLETE_PERCENT: "Hoàn thành",
        
        ISFINISHED: "Hồ sơ đã kết thúc",
        SEARCH: "Tìm kiếm Hồ sơ",
        SEARCH_NOT_FOUND: "Không tìm thấy hồ sơ",
        IS_NEW: "New",
        IS_URGENT: "Urgent",
        IS_ROLLBACK: "Backed",
        IS_APPEND: "Append",
        TIME: "Thời gian đến",
        SEND_USER: "User Sent",
        CREATED_USER: "User Created",
        EXISTING_FILE: "Xem file có sẵn"
    },
    ACCOUNT: {
        LOGIN: "Login",
        LOGIN_FAILED: "User name or password is wrong.",
        LOGIN_USERNAME: "User name",
        LOGIN_PASSWORD: "Password",
        CHANGE_PASSWORD: "Change password",
        OLD_PASSWORD: "Old Password",
        NEW_PASSWORD: "New Password",
        RETYPE_PASSWORD: "Retype Password",
        WRONG_PASSWORD: "Old Password is wrong",
        CHANGE_PASSWORD_SUCCESS: "Changed password successfully!",
        SIGNOUT: "Sign out"
    },
    REPORT: {
        BRANCH: "Báo cáo theo Chi nhánh",
        DEPARTMENT: "Báo Cáo theo Phòng ban",
        USERS: "Báo cáo theo Nhân viên trong phòng",
        USER: "Báo cáo theo Nhân viên",
        KPI_NUMBER: "Số lượng hồ sơ",
        KPI_SALE: "Doanh số giải ngân",
        KPI_SALE_AVAILABLE: "Tổng Hạn mức được duyệt",
        PROPERTY_BEGIN: "Từ ngày",
        PROPERTY_END: "Đến ngày"
    },
   
}
var EVENT = {    
    SHOW_USERS: "organization:detail",
    APPLICATION_INBOX_TOTAL: "application:inbox_total",
    CHANGE_MAIN_VIEW: "main:change_main_view"
}
var SETTING = {
    THEME: "office",
}

var CONSTANT = {
    APPLICATION_TYPE_PROCESSING: 1,
    APPLICATION_TYPE_SENT: 2,
    APPLICATION_TYPE_MANAGEMENT: 3,
    APPLICATION_TYPE_SEND: 1,
    APPLICATION_TYPE_DEPARTMENT_SEND: 2,
    INBOX_VIEW: 'viewmodels/inbox',
    APPLICATION_VIEW: 'viewmodels/application_detail',
    UUID_EMPTY: '00000000-0000-0000-0000-000000000000',
    ORGANIZATION_TYPE_BRANCH: 1,
    ORGANIZATION_TYPE_DEPARTMENTS: 2,
    ORGANIZATION_TYPE_SUBDEPARTMENTS: 3,
    ORGANIZATION_TYPE_DEPARTMENT: 4,
    ORGANIZATION_TYPE_SUBDEPARTMENT: 5,
    PRODUCT_TYPE_PRODUCT: 1,
    PRODUCT_TYPE_PRODUCTFORM: 2,
    PRODUCT_TYPE_PRODUCTFILEATTACHMENT: 3,
    DATAMODEL_BASE: 1,
    DATAMODEL_ARRAY: 2,
    DATAMODEL_COMPUTE: 3,
    DATAMODEL_FUNCTION: 4
}